server:
  port: 8081

spring:
  application:
    name: im-route
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        max-wait: -1
        max-idle: 8
        min-idle: 0