server:
  port: 8082

spring:
  application:
    name: im-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-wait: -1
        max-idle: 8
        min-idle: 0
# im configuration
im:
  ws-port: 2408
  zk:
    address: 127.0.0.1:2181
    timeout: 150000